# Your Website Title
title: 김소희의 포트폴리오

# Your Website URL
url: 'http://sosodoit.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
#ga_index: UA-XXXXXXXX-X
#ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: 김소희
tagline: 예술하는 데이터분석가
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Full Stack Developer, IoT, Reverse Engineering
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
#email: you.email.email@gmail.com
website: sosodoit.github.io # do not add http://
#linkedin: realmelvinchng
github: sosodoit
#twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm